name: C - Terraform Ouput

on: workflow_dispatch

jobs:
  terraform:
    name: "Terraform output"
    env:
      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN}}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - name: Verify Terraform version
      run: terraform --version

    - name: Terraform init
      run: |
        terraform init -input=false \
        -backend-config="access_key=${{ secrets.SPACES_ACCESS_KEY_ID}}" \
        -backend-config="secret_key=${{ secrets.SPACES_SECRET_ACCESS_KEY}}" \
        -backend-config="bucket=$S3_BUCKET"

    - name: Terraform validation
      run: terraform validate

    - name: Terraform output
      run: terraform output
