name: X - Terraform Destroy

on: workflow_dispatch

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Terraform init
      env:
        DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN}}
        S3_BUCKET: "20220226tfstate"
      run: terraform init -input=false -backend-config="access_key=${{ secrets.SPACES_ACCESS_KEY_ID}}" -backend-config="secret_key=${{ secrets.SPACES_SECRET_ACCESS_KEY}}" -backend-config="bucket=$S3_BUCKET"

    - name: Terraform destroy
      env:
        DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      run: terraform apply -destroy -auto-approve -input=false
