name: X - Terraform Destroy

on: workflow_dispatch

jobs:
  terraform:
    name: "Terraform destroy"
    env:
      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN}}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: DigitalOcean doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Terraform init
      run: |
        terraform init \
          -input=false \
          -backend-config="access_key=${{ secrets.SPACES_ACCESS_KEY_ID}}" \
          -backend-config="secret_key=${{ secrets.SPACES_SECRET_ACCESS_KEY}}" \
          -backend-config="bucket=${{ secrets.S3_BUCKET}}"

    - name: Terraform destroy
      run: |
        terraform apply \
          -destroy -auto-approve -input=false \
          -var "pub_key_data=${{ secrets.ID_RSA_WEBODM}}"
