name: Z - Terraform State Remove

on: workflow_dispatch

jobs:
  terraform:
    name: "Terraform state remove"
    env:
      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN}}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Use S3cmd
      uses: s3-actions/s3cmd@v1.1

    - name: S3 remove bucket file
      run: s3cmd rm s3://20220226tfstate/terraform.tfstate