name: Z - Terraform State Remove

on: workflow_dispatch

jobs:
  terraform:
    name: "Terraform state remove"
    env:
      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN}}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: S3cmd actions
      uses: mltframework/s3cmd-action@main
        with:
          args: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: S3 remove bucket file
      run: s3cmd rm s3://20220226tfstate/terraform.tfstate